export const STORAGE_KEYS = {
    links: 'links',
    groups: 'groups',
    settings: 'settings',
    profiles: 'profiles',
    syncWorkerUrl: 'syncWorkerUrl',
    syncApiCode: 'syncApiCode',
    syncProfile: 'syncProfile',
    syncMode: 'syncMode',
    syncDelaySeconds: 'syncDelaySeconds',
    syncReady: 'syncReady',
    syncRevision: 'syncRevision',
    syncStatus: 'syncStatus',
    syncStatusType: 'syncStatusType',
    syncVerifyStatus: 'syncVerifyStatus',
    syncVerifyStatusType: 'syncVerifyStatusType',
    syncLiveStatus: 'syncLiveStatus',
    recentPage: 'recentPage',
    faviconCache: 'faviconCache'
};
