export function getDomRefs() {
    return {
        quickActions: document.getElementById('quick-actions'),
        addCurrentBtn: document.getElementById('add-current-btn'),
        quickActionStatus: document.getElementById('quick-action-status'),
        pinnedGrid: document.getElementById('pinned-grid'),
        groupTabs: document.getElementById('group-tabs'),
        selectedGrid: document.getElementById('selected-grid'),
        settingsBtn: document.getElementById('settings-btn'),
        contextMenu: document.getElementById('context-menu'),
        modalOverlay: document.getElementById('modal-overlay'),
        modalTitle: document.getElementById('modal-title'),
        modalBodyLink: document.getElementById('modal-body-link'),
        modalBodyGroup: document.getElementById('modal-body-group'),
        inputUrl: document.getElementById('input-url'),
        inputName: document.getElementById('input-name'),
        inputGroup: document.getElementById('input-group'),
        inputGroupName: document.getElementById('input-group-name'),
        modalCancel: document.getElementById('modal-cancel'),
        modalSave: document.getElementById('modal-save'),
        settingsOverlay: document.getElementById('settings-overlay'),
        settingIconSize: document.getElementById('setting-icon-size'),
        settingIconSizeVal: document.getElementById('setting-icon-size-val'),
        cleanupFaviconsBtn: document.getElementById('cleanup-favicons'),
        settingsClose: document.getElementById('settings-close'),
        gistTokenInput: document.getElementById('setting-gist-token'),
        verifyGistTokenBtn: document.getElementById('verify-gist-token'),
        gistVerifyStatus: document.getElementById('gist-verify-status'),
        syncPush: document.getElementById('sync-push'),
        syncPull: document.getElementById('sync-pull'),
        syncStatus: document.getElementById('sync-status')
    };
}
