name = "extension"
main = "src/index.js"
compatibility_date = "2026-05-26"
workers_dev = true

[[r2_buckets]]
binding = "EXTENSION_BUCKET"
bucket_name = "extension-sync"

[triggers]
crons = ["0 * * * *"]
